stages:
- test
- deploy

pre-deployment-checks:
  stage: test
  script:
    - echo "Test succeeded"

kfp-pipeline-deployment:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production